=== api-evangelist/adobe-experience-cloud/json-schema/target-api-activity-list-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/adobe-experience-cloud/refs/heads/main/json-schema/target-api-activity-list-schema.json",
  "title": "ActivityList",
  "description": "ActivityList schema",
  "type": "object",
  "properties": {
    "total": {
      "type": "integer"
    },
    "offset": {
      "type": "integer"
    },
    "limit": {
      "type": "integer"
    },
    "activities": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": [
              "ab",
              "xt",
              "mvt",
              "ap"
            ]
          },
          "state": {
            "type": "string",
            "enum": [
              "approved",
              "deactivated",
              "archived"
            ]
          },
          "priority": {
            "type": "integer"
          },
          "modifiedAt": {
            "type": "string",
            "format": "date-time"
          },
          "startsAt": {
            "type": "string",
            "format": "date-time"
          },
          "endsAt": {
            "type": "string",
            "format": "date-time"
          }
        }
      }
    }
  }
}

=== api-evangelist/adobe-experience-cloud/examples/target-api-activity-list-example.json
{
  "total": 89,
  "offset": 83,
  "limit": 26,
  "activities": [
    {
      "id": 24,
      "name": "Example Name",
      "type": "ab",
      "state": "approved",
      "priority": 81,
      "modifiedAt": "2025-03-15T14:30:00Z",
      "startsAt": "2025-03-15T14:30:00Z",
      "endsAt": "2025-03-15T14:30:00Z"
    }
  ]
}
